### ISSUE TITLE
404 error on latest release

### ISSUE THREAD

**Issue by skobylite** [w0lfschild/MacForge#1]
Hi - 404 error on the latest release link: https://github.com/w0lfschild/app_updates/raw/master/MacPlus/MacPlus_master.zip

Thanks!

**Comment by w0lfschild** [comment]
It has not been released yet.

**Comment by sammarcus** [comment]
What are the differences between MacForge and mySIMBL?

**Comment by w0lfschild** [comment]
The main differences are:

MacForge is using MachInject instead of SIMBL
MacForge works on 10.14+, mySIMBL doesn't work on 10.15 and works questionably on 10.14
MacForge can installing more than just plugins
MacForge has a refreshed UI
