### ISSUE TITLE
Problem: MacForgeHelper crashes SecurityAgent.

### ISSUE THREAD

**Issue by kingtosh** [w0lfschild/MacForge#10]
In loading MacForgeHelper, it crashes SecurityAgent. And the window of input youser name and pass freeze on the top level. Another windows have gone behind.

So, please fix this problem.

**Comment by w0lfschild** [comment]
You'd need to go into more detail. What is SecurityAgent? 

Also this sounds like maybe a specific plugin issue?

**Comment by kingtosh** [comment]
this is a path of SecurityAgent.
/System/Library/Frameworks/Security.framework/Versions/A/MachServices/SecurityAgent.bundle
Apple's system protecting function.
Inputting user name and password, it is loaded by MacOS.

**Comment by kingtosh** [comment]
![screen](https://user-images.githubusercontent.com/10953627/64059411-09020a00-cbf7-11e9-8e31-7d7421c871f6.jpg)

**Comment by w0lfschild** [comment]
Okay interesting.

macOS version?
Do you have any plugins loaded?
Do you have System Integrity Protection on or off?

**Comment by kingtosh** [comment]
Sorry!, I forgot them.

my MacOS is 10.12.6 (16G2128), and using Afloat.
Of course, I had turned off SIP, but MacForge tells SIP still on (i don't know why).

**Comment by w0lfschild** [comment]
If you turn off afloat does this issue still occur?

**Comment by kingtosh** [comment]
![スクリーンショット 2019-08-31 14 29 12](https://user-images.githubusercontent.com/10953627/64059668-f76f3100-cbfb-11e9-94be-9c4734211c51.png)

**Comment by kingtosh** [comment]
Turning off afloat, this didn't occur.

**Comment by kingtosh** [comment]
So, just afloat's a problem is this, isn't it?

**Comment by w0lfschild** [comment]
That would be my guess. In order to stop it from loading into SecurityAgent there would probably need to be changes to made to Afloat to look for classes specific to that and avoid touching those windows.
