### ISSUE TITLE
MacForge incorrectly reports itself uninstalled when another copy of MacForge.app is in ~/.Trash

### ISSUE THREAD

**Issue by pcr910303** [w0lfschild/MacForge#12]
## Bug Report

**Current Behavior**
MacForge reports itself uninstalled when another copy of MacForge.app is in ~/.Trash.

**To Reproduce**
1. Download another copy of MacForge.app.
2. Trash the other copy to ~/.Trash.
3. Trash any other file, and MacForge will report itself uninstalled.

**Expected behavior/code**
MacForge should correctly not report itself uninstalled.

**Screenshots**
![image](https://user-images.githubusercontent.com/37990858/64314843-53b2c600-cfeb-11e9-80fa-243cb9cd14f5.png)

**Environment**
- MacForge version(s): version 0.10.3 (1035)
- OS version: macOS 10.14.6
- Plugins: currently none running

**Possible Solution**
I think it would be fine if MacForge just wouldn't check if it's uninstalled.
Having an uninstall button in MacForge would be better. (No automatic detection)

**Comment by w0lfschild** [comment]
Most likely I'll just add a check to see if the helper itself is in the trash. Even though this app is somewhat targeted at a power user (someone willing to disable SIP and AMFI) the goal is for it to be simple to use and most people would consider throwing an application in the trash uninstalling it.

**Comment by w0lfschild** [comment]
0.11.1 will now only show that prompt if there is no longer a file where the helpers bundle was when it launched.
