### ISSUE TITLE
Flashlight does not work with MacForge in Catalina

### ISSUE THREAD

**Issue by bwt615** [w0lfschild/MacForge#13]
Beta 7 - Does not load commands via spotlight like expected

Really unclear what the System Info tab is saying. Application blacklist shows mySimbl which makes me wonder whether that load is being blocked. SIP is disabled.

**Comment by w0lfschild** [comment]
The blacklist is a list of apps that MacForge will not try to load into.

Flashlight loads into the Spotlight application.

It's most likely that Flashlight needs updating for Catalina.

**Comment by bwt615** [comment]
Ah. Any plans to fix that? Any way to transfer this bug over there?

On Sep 5, 2019, at 4:28 PM, Wolfgang Baird <notifications@github.com> wrote:

﻿

The blacklist is a list of apps that MacForge will not try to load into.

Flashlight loads into the Spotlight application.

It's most likely that Flashlight needs updating for Catalina.

**Comment by w0lfschild** [comment]
I will look into this at some point, yes.

**Comment by w0lfschild** [comment]
Just gonna cross link the same issue from the Flashlight repo. I'm willing to PayPal someone $20 if they can get it running well on Catalina.

https://github.com/w0lfschild/Flashlight/issues/65

**Comment by real-cereal-boy** [comment]
U need to grant the program full access, turn off disk check and encryption, then go into recovery, (cmd + r) Select terminal from the drop down menu, type csrutil disable. 

At some point you might have to sudo the program in terminal. Apple has been very serious with Catalina and its Security, personally I do not like MacOS Catalina and will be willing to help anyone downgrade as well

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/Flashlight/issues/65#issuecomment-569994756
