### ISSUE TITLE
'damaged and could not be opened...'

### ISSUE THREAD

**Issue by jxj24** [w0lfschild/MacForge#14]
Version 0.11.3, on Sierra 10.12.6, SIP disabled.

Re-DLed, still can't launch. 

Thanks

**Comment by TheBingPlays** [comment]
had the same problem this solved it for me

run this in terminal
xattr -cr /Downloads/MacForge.app

**Comment by w0lfschild** [comment]
I'll look into this after I get off work.

**Comment by TheBingPlays** [comment]
I still can't get iMessage parity to work either way. With either MacForge or mySIMBIL. Neither let me send effects

**Comment by w0lfschild** [comment]
@TheBingPlays 

Is it not loading at all or are the effects just not working?

**Comment by TheBingPlays** [comment]
Loads in imessage ok but no effects. No (sent with echo) or anything. I click on the effect I want to use and it does nothing. The menu is still up and when I push enter to send, again no (sent with *effect*) at all.

**Comment by jxj24** [comment]
> had the same problem this solved it for me
> 
> run this in terminal
> xattr -cr /Downloads/MacForge.app

 Thanks, that fixed it.

**Comment by TheBingPlays** [comment]
@w0lfschild 
if youd like to see what im talking about
https://imgur.com/a/OrJWfeK

**Comment by TheBingPlays** [comment]
@jxj24 

> > had the same problem this solved it for me
> > run this in terminal
> > xattr -cr /Downloads/MacForge.app
> 
> Thanks, that fixed it.

no problem

**Comment by w0lfschild** [comment]
@TheBingPlays 

Odd. What version of macOS? It's working fine for me on the latest Catalina beta and AFAIK it should still be working on all old version as well.

@jxj24 

Original issue has been fixed so I'm closing this thread.

**Comment by TheBingPlays** [comment]
Macos high Sierra
