### ISSUE TITLE
Apps become unresponsive when using Afloat

### ISSUE THREAD

**Issue by relin1226** [w0lfschild/MacForge#19]
It worked well for weeks but yesterday it suddenly stop every app when running. I only used afloat. So I tried to uninstall it. After reboot everything  goes well, but when i install afloat again it stop other apps again(not in responding). I cannot even open activity monitor to stop it.(not in responding when launch any app)

mac version 10.14.6 mojave

-----------------------

A temporary solution for me is open macforge and open the app I want to use afloat, then quit macforge, launch clean my mac and stop every app not in responding (if I keep macforge running while open clean my mac, it will become not in responding again) then everything goes well and I can use afloat in that app only

**Comment by w0lfschild** [comment]
Maybe try [AfloatX](https://www.macenhance.com/mflink?macforge://github.com/w0lfschild/macplugins/raw/master/com.github.jslegendre.AfloatX)?

**Comment by adamwinn** [comment]
I'm seeing this, but I dont have Afloat installed.  Also the app icon in the menu bar is invisible, but if I hover over where it is, the cursor beachballs.

![image](https://user-images.githubusercontent.com/3028964/70313746-6ba90a00-17d3-11ea-9bfb-83e2d5148f02.png)

**Comment by w0lfschild** [comment]
@adamwinn That looks like the helper is freezing. Are other apps freezing for you as well?

**Comment by adamwinn** [comment]
No, not that I've noticed

**Comment by minimum91** [comment]
> I'm seeing this, but I dont have Afloat installed. Also the app icon in the menu bar is invisible, but if I hover over where it is, the cursor beachballs.
> 
> ![image](https://user-images.githubusercontent.com/3028964/70313746-6ba90a00-17d3-11ea-9bfb-83e2d5148f02.png)

I am experiencing the same behaviour right now.

**Comment by adamwinn** [comment]
For what it's worth, mine is no longer freezing like that.  I think it has upgraded since I posted.  I'm on `0.13.2` now

**Comment by w0lfschild** [comment]
Think I've got a fix for beachballing / crashing helper that will be coming out soon.

**Comment by w0lfschild** [comment]
Should be fixed in 0.14.1
