### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by Patrik-svobodik** [w0lfschild/MacForge#2]
FConvenience.h is missing,  there are some problems with developer profiles. 

btw application.xib is named appliaction.xib

**Comment by w0lfschild** [comment]
FConvenience.h is in the project here so not sure how it's missing. Maybe for some reason or another it's trying to use a hard path including my username.

It's codesigned using my developer profile so if you want to build it yourself you'd need to replace my profile with your own.

Thanks for pointing out the appliaction typo.

**Comment by drewauff** [comment]
I can't build either, just sits trying to sign forever..

**Comment by Patrik-svobodik** [comment]
Found a solution, you have to sign multiple apps, not only the MacPlus
čt 30. 8. 2018 v 16:04 odesílatel drewauff <notifications@github.com>
napsal:
