### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by Magwin70** [w0lfschild/MacForge#20]
## Feature Request... 

🤓Option to hide the MacForge menu bar icon would be nice please 🤓🙏

**Comment by w0lfschild** [comment]
Yeah I'm pretty sure this can be done pretty easily.

**Comment by w0lfschild** [comment]
This is live in [0.13.2](https://github.com/w0lfschild/app_updates/raw/master/MacForge/MacForge.zip)
