### ISSUE TITLE
MacForge: cleanHUD (OS Catalina)

### ISSUE THREAD

**Issue by af97272** [w0lfschild/MacForge#21]
i am on OS 10.15.1, and cleanHUD isnt showing up, it works but there is no visual indicator. I am running cleanHUD version 0.7.2. MacForge also only picks up my AMFI disabled, but not my SIP which is also disabled

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cleanHUD/issues/9#issuecomment-558396262
