### ISSUE TITLE
Enabling any extension causes all apps to go into crash/reopen loop

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/MacForge#22]
## Bug Report

**Current Behavior**
I replaced mySIMBL with MacForge on my Mac Pro 2010 running 10.12.6 and since, with any extension enabled, everything will go into a constant crash/reopen loop. Removing extensions and or enabling SIP prevents the crash/relaunch loop.

1. Go to Manage
2. Click on checkbox for any extension
4. Everything, including SystemUIServer goes into crash/relaunch loop

- MacForge version: v0.13.2
- OS version: macOS 10.12.6
- Plugins: any
- SIP disabled, AMFI enabled

Tried uninstalling all components from mySIMBL, as well as removing all MacForge related components, reinstalling and adding the plugins again to no avail. Crash loop still persists.

Can provide access for debugging purposes to machine if needed.

[Crashloop.mov.zip](https://github.com/w0lfschild/MacForge/files/3935376/Crashloop.mov.zip)

**Comment by w0lfschild** [comment]
If you're running 10.12.6 

You might want to try mySIMBL instead.  

https://github.com/w0lfschild/mySIMBL
