### ISSUE TITLE
Unable to inject into Library Validated apps

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/MacForge#23]
## Bug Report

Apps like Safari and Mail are unable to load plugins.

Steps to enable injection into Library-Validated apps have been made:
SIP and AMFI disabled.

At first install of MacForge (after removing mySIMBL), this actually worked for literally half a minute and I could see options for Afloat and Fullscreener appear, but after that first minute, the options dissapeared and never appeared again, regardless of any attempts to disable, re-enable SIP and/or AMFI.

- MacForge v0.13.2
- macOS 10.14.6
- Plugins: Afloat, fullscreener

For the good of debugging I can provide VNC access to my machines at your request.

**Comment by w0lfschild** [comment]
Have you restarted after disabling AMFI?

**Comment by minimum91** [comment]
> Have you restarted after disabling AMFI?

Absolutely.

**Comment by w0lfschild** [comment]
Maybe post a screenshot of your 'System' tab in MacForge?
Is the helper crashing / freezing?

**Comment by w0lfschild** [comment]
Should be fixed in 0.14.1
