### ISSUE TITLE
Colorful Sidebar - customisation

### ISSUE THREAD

**Issue by gavinbrockis** [w0lfschild/MacForge#28]
liking this plugin and my newly recolourised Sidebar - thanks

can you elaborate on the process for customising the icons? cheers

**Comment by w0lfschild** [comment]
Open the icon plist that corresponds with your version of macOS in 

`/Library/Application Support/MacEnhance/Plugins/colorfulSidebar9.bundle/Contents/Resources`

Once you have that open simply add an array to the dictionary with the key being the path to an icon and the items in the array being the path to the folder you want themed

Example

I want to theme the folder `~/Documents` with the image `~/Desktop/coolanimepicture.png`

I would add :

```
<key>~/Desktop/coolanimepicture.png</key>
<array>
	<string>~/Documents</string>
</array>
```

You can also edit the existing keys if you want to change what's already being used.

IIRC you'll need to restart Finder after making changes to see them applied.

**Comment by gavinbrockis** [comment]
Hi, I’ve had to reinstall MacOS - what is my Colourful Sidebar license please? Thanks, Gavin

**Comment by w0lfschild** [comment]
@gavinbrockis what's the email you used to purchase the license?
