### ISSUE TITLE
Hooking is disabled after a while

### ISSUE THREAD

**Issue by haniag** [w0lfschild/MacForge#32]
## Bug Report

**Current Behavior**
I have latest binary installed (0.14.1). After a while, I notice that tweaks no longer hook.
SIP is disabled, but AMFI is enabled in macOS.
I am hooking non-App Store apps and macOS.
Menu bar is showing.

**To Reproduce**
You can try to reproduce with any tweak.

**Expected behavior/code**
Hooks to be implemented.

**Screenshots**
N/A

**Environment**
- MacForge version(s): 0.14.1
- OS version: macOS 10.14.6
- Plugins: cleanHUD 0.10.6, in addition to other plugins running on non-App Store apps

**Possible Solution**
Re-open MacForge app results in everything working again.

**Additional context**

**Comment by w0lfschild** [comment]
It's likely an app that fails to accept injection crashing / hanging the helper

**Comment by w0lfschild** [comment]
Does this still happen with the latest version?

**Comment by haniag** [comment]
I have been using it for a day, and seems ok.
