### ISSUE TITLE
Built and Tested MacForge

### ISSUE THREAD

**Issue by npyl** [w0lfschild/MacForge#5]
Just wanted to give a small review even though I know this is a beta software and not released yet. :) 

So far works great!  I especially like the fact that macOS doesn't ask for permission every time MacForge tries to inject a plugin like it used to with Mojave/mySIMBL.

Even my plugin (EnhanceDiskUtil) worked that somehow compatibility broke when I updated to Mojave.

Keep up the good work.

**Comment by w0lfschild** [comment]
Thanks for the feedback!
