### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by FreddieOliveira** [w0lfschild/MacForge#6]
Clicking on `System Info -> Unistall SIMBL` does not remove any created folder/file nor kill any of the SIMBL process. After clicking the Uninstall button and running

`sudo find / -iname "*simb*" 2>/dev/null`

it's still possible to see residual files left on the system. Also killing SIMBL process is a pain in the ass, since it restarts automatically

**Comment by w0lfschild** [comment]
This project does not use SIMBL.

For removing mySIMBL stuff:

The SIMBL agent is a launchagent that will restart itself so first you have to unload it.

```
launchctl unload /Library/LaunchAgents/net.culater.SIMBL.Agent.plist
killall SIMBLAgent
```

In terms of files you want to remove these (if they exist):

```
"/Library/Application Support/SIMBL"
"/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
"/Library/ScriptingAdditions/SIMBL.osax"
"/Library/ScriptingAdditions/EasySIMBL.osax"
"/System/Library/ScriptingAdditions/SIMBL.osax"
"/System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist"
"$HOME/Library/ScriptingAdditions/SIMBL.osax"
"$HOME/Library/ScriptingAdditions/EasySIMBL.osax"
"/Library/PrivilegedHelperTools/com.w0lf.MacForge.Injector"
"/Library/PrivilegedHelperTools/com.w0lf.MacForge.Installer"
"/Library/LaunchDaemons/com.w0lf.MacForge.Injector.plist"
"/Library/LaunchDaemons/com.w0lf.MacForge.Installer.plist"
"/Library/Frameworks/mach_inject_bundle.framework"
```
