### ISSUE TITLE
pop error window showed "NSInvalidArgumentException" when use selenium open chrome

### ISSUE THREAD

**Issue by Jingxizi** [w0lfschild/MacForge#9]
hello, w0lfschild
when I use selenium to open a chrome window in unvisibleway, MacForce will pop a window showed NSInvalidArgumentException. MacForce only installed afloat.

code is: 
chrome_options = Options()

chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('window-size=1920x3000')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--hide-scrollbars')
chrome_options.add_argument('blink-settings=imagesEnabled=false')
chrome_options.add_argument('--headless')//make chrome unvisible
driver = webdriver.Chrome(options=chrome_options)

mySIMBL didn't have this problem.

**Comment by Jingxizi** [comment]
@w0lfschild
![Snipaste_2019-09-02_09-59-39](https://user-images.githubusercontent.com/24663392/64086121-fad3fb00-cd68-11e9-8ad6-6c90b8055138.jpg)

**Comment by w0lfschild** [comment]
Should be fixed in 0.10.3
